#!/bin/bash

# Set your configuration options in /etc/default/rpi-timelapse

# directory check
if [[ -z "$SAVEDIR" ]]; then
    SAVEDIR=/home/pi/timelapse
fi

# delay check
if [[ -z "$DELAY" ]]; then
    DELAY=60
fi

# threshold check
if [[ -z "$DARKNESS_THRESHOLD" ]]; then
    DARKNESS_THRESHOLD=1500
fi

# log to logger
function logit {
    logger -t "rpi-timelapse" "$1"
}

logit "starting..."
logit "save directory: ${SAVEDIR}"
logit "delay: ${DELAY}"
logit "darkness threshold: ${DARKNESS_THRESHOLD}"

# loop and take photos
while [ true ]; do

    hour=$(date +"%H")

    #if [ $hour -ge 5 ] && [ $hour -le 20 ]; then

        directory=$SAVEDIR/$(date +"%Y-%m-%d")

        # make sure directory exists
        if [ ! -d "$directory" ]; then
            mkdir -p $directory
            if [ $? -ne 0 ]; then
                logit "Unable to create directory: ${directory}"
                exit 1
            fi
        fi

        filename=$(date +"%Y-%m-%d_%H-%M-%S").jpg

        /usr/bin/env raspistill -o $directory/$filename

        if [ $? -ne 0 ]; then
            logit "Unable to use raspistill to take a photo. Error codefrom raspistill: $?"
            exit 1
        fi

        # check if image is "dark"
        darknessValue=`convert ${directory}/${filename} -format "%[mean]" info:`
        # convert to an int
        darknessValue=$( printf "%.0f" $darknessValue )
        if [ "$darknessValue" -lt "$DARKNESS_THRESHOLD" ]; then
            rm "${directory}/${filename}"
            logit "Photo ${filename} was too dark (darkness value: ${darknessValue}). It has been deleted."
        else
            logit "Photo saved to ${filename}. Darkness value: ${darknessValue}"
        fi

    #else
        #logit "Not time for a photo."
    #fi

    sleep $DELAY;

done;
